# Generated by Django 4.2.15 on 2024-08-22 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishmodel', '0002_chef_dishes_rating_alter_dishes_dish_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
