# Generated by Django 4.2.15 on 2024-08-22 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishmodel', '0003_alter_dishes_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=15)),
                ('postal_code', models.IntegerField()),
                ('street_no', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='chef',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dishmodel.address'),
        ),
    ]
