# Generated by Django 4.2.15 on 2024-08-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(default=23, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
