# Generated by Django 4.2.15 on 2024-08-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileupload',
            name='userimage',
            field=models.ImageField(upload_to='images'),
        ),
    ]
